### ISSUE TITLE
Add a select menu class for the list command to be able to choose an asset from

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/cli-agent#133]

**Comment by sambhavnoobcoder** [comment]
Hey @Bishoy-at-pieces ,
just confirming , this used to be the output when running the list command for assets earlier :
<img width="220" alt="Screenshot 2024-07-20 at 3 05 42 AM" src="https://github.com/user-attachments/assets/e5f9a956-7b9b-4218-8b66-cdede534cb3d">

but after the change I made , it looks like this : 
<img width="515" alt="Screenshot 2024-07-20 at 3 07 11 AM" src="https://github.com/user-attachments/assets/e1eec00a-dcde-4f1b-9837-49d9d01eeea7">

is this the change you were seeking in this issue ? if yes , then I can push the code . if not , kindly do tell me the changes you wanted here and I'll make them accordingly.

**Comment by Bishoy-at-pieces** [comment]
#140

**Comment by sambhavnoobcoder** [comment]
aha , got . thanks . on it .

**Comment by Bishoy-at-pieces** [comment]
Let me know if you want the code snippet for making select menus and you can continue on it and make it working in the list models,assets or any other index based  selection

**Comment by sambhavnoobcoder** [comment]
yeah sure , if you have that , I'd rather work with that rather than reinventing the wheel . I'll try to implement that for the assets , apps and models , those three are what I believe are the index based sections in the list_command code

**Comment by Bishoy-at-pieces** [comment]
Yupp sure here you go https://bishoyatpieces.pieces.cloud/?p=c787439ee9,
but before you add anything I would like to discuss it in discussion #140 and know how it will exactly work.
I think the open command should be removed now since we won't use it also the change model we will need to discuss it first before you do anything

**Comment by Bishoy-at-pieces** [comment]
@sambhavnoobcoder also feel free to share your thoughts in #140

**Comment by Bishoy-at-pieces** [comment]
@sambhavnoobcoder let me know if you faced an issue or you need any sort of help from me

**Comment by sambhavnoobcoder** [comment]
sure , working on it rn , will inform you if I face any issues , will most probably share a screen recording to verify if the behaviour after the change is as expected .

**Comment by sambhavnoobcoder** [comment]
https://github.com/user-attachments/assets/95c9b307-dad3-4cef-bd35-e3e2f13b40db

@Bishoy-at-pieces does this replicate the expected behaviour ?

**Comment by Bishoy-at-pieces** [comment]
Yes nice open an issue for it!

**Comment by sambhavnoobcoder** [comment]
okay , so just to be clear what you are saying is that for this issue , we just want the code that allows us to select the asset from the possible list of assets , using the select menu , and then using separate line of code , we call the open_asset command from the AssetCommand class to open the selected asset as done previously ?and we can integrate the open_asset to work from inside the select menu directly later ?

**Comment by Bishoy-at-pieces** [comment]
For later I would like to change the behavior of the open command.
Just for now, when you select an asset you gonna run the open_asset method in the AssetsCommands class

**Comment by sambhavnoobcoder** [comment]
okay got it . I may have overstepped a bit here, but no worries , I'll make it behave accordingly for the timebeing , and will raise a pr accordingly . we can work to change the behaviour of the open command in the future .

**Comment by Bishoy-at-pieces** [comment]
Thank you°

**Comment by sambhavnoobcoder** [comment]
created PR #149 to address this issue . kindly give it a look .
