### ISSUE TITLE
Create executable file for each release?

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/cli-agent#144]
Instead of downloading the tool from pypi we can create an executable file to download the cli tool

**Comment by mdex-geek** [comment]
Hey bishoy I am interested in this issue

**Comment by Bishoy-at-pieces** [comment]
Great how will you do it?
Also we need to add it to the pipeline we can also use pyinstaller

**Comment by Bishoy-at-pieces** [comment]
You can go and try it

**Comment by mdex-geek** [comment]
> Great how will you do it?
> Also we need to add it to the pipeline we can also use pyinstaller
> 

After search about this issue I get answer of pyinstaller

**Comment by Bishoy-at-pieces** [comment]
Pyinstaller won't append the executable to the path we can discuss that and how we want to do it
You will need to do 
Path/to/executable run
It should be pieces

Also we will need uninstall and updater

**Comment by Bishoy-at-pieces** [comment]
@mdex-geek Keep us in the loop, and let me know how you did here

**Comment by mdex-geek** [comment]
Uploading Recording 2024-07-26 102343.mp4…

hey i create a exe file and it run 

> Pyinstaller won't append the executable to the path You will need to do `path/to/executable run` It should be `pieces run`
> 
> Also we will need uninstall and updater

but i do not understand this

**Comment by Bishoy-at-pieces** [comment]
So how can we delete/update the cli-tool?
Plus we need to append to the path? How can we do this also?

**Comment by Bishoy-at-pieces** [comment]
Adding it to the path means we will do `pieces run` instead `path/to/executable run`

**Comment by Bishoy-at-pieces** [comment]
https://cx-freeze.readthedocs.io/en/stable/
this is amazing tool worth checking!
Let me know how is everything going @mdex-geek no worries no rush take your time!
