### ISSUE TITLE
Building and Running

### ISSUE THREAD

**Issue by nathan-courtney-pieces** [pieces-app/cli-agent#15]
Currently building out in CI on branch `testing_ci`

Downloading the Github artifacts and installing via `.whl` file results in this error: 

➜  pieces
Traceback (most recent call last):
  File "/Users/nathancourtney/.pyenv/versions/3.12.1/bin/pieces", line 5, in <module>
    from app import main
ModuleNotFoundError: No module named 'app'

Am I missing something? Is there some sort of dependencies that are not included in here? Assuming that everything is being configured via `setuptools` as their is no `__init__.py` file.

**Comment by hal-8999-alpha** [comment]
Is this still relevant?
