### ISSUE TITLE
Change the open_asset behavior 

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/cli-agent#150]
we want instead of saving the snippet to file we want to open it in the terminal (print the content) don't forget the code highlighting!!
and we can add a flag to the list_command to open the asset in the editor (eg vscode)

How will it work?

1- so we can use the rich and pygments libraries for code highlighting and we can print the content higlighted 
2- If the user wrote a flag `eg -e` to the list command it should save it and open it to the user prefered editor (we can get a config command to configure the fav editor eg vcode)
we can do like git and get the entery point of that editor eg `code "path/to/snippet/saved"` or `subl `path/to/snippet/saved``

**Comment by sambhavnoobcoder** [comment]
https://github.com/user-attachments/assets/a1302184-8a30-43a7-96ca-c8373211b5a2


Hey @Bishoy-at-pieces , is this the expected behaviour for the point 1 in this issue ,i.e, opening code terminal with code highlighting without saving it as a snippet ?

**Comment by Bishoy-at-pieces** [comment]
Looks Great!!!
Please let us know before you begin in an issue thank you

**Comment by sambhavnoobcoder** [comment]
sure , I'll work on the command for editor ,and open a pr when that's done as well

**Comment by sambhavnoobcoder** [comment]
https://github.com/user-attachments/assets/d28fe63f-89a3-4c98-a6be-98657a620b8f

Got the second feature running as well , will raise the PR shortly

**Comment by sambhavnoobcoder** [comment]
raised PR #152 for the same , kindly have a look at it
