### ISSUE TITLE
Fix the test for the list command

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/cli-agent#154]

**Comment by sambhavnoobcoder** [comment]
can I take up this issue ? I think I have a PR that could successfully close this issue .
<img width="910" alt="Screenshot 2024-07-30 at 12 02 50 AM" src="https://github.com/user-attachments/assets/656bca11-3c63-4d7c-a4ec-de9294da5a4e">

**Comment by Bishoy-at-pieces** [comment]
Great

**Comment by sambhavnoobcoder** [comment]
opened #159 to solve this issue . kindly give it a look.
