### ISSUE TITLE
Docs: open command

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/cli-agent#156]
Documentation for the new stuff in the open command
1. Editor config
2. -e flag

**Comment by sambhavnoobcoder** [comment]
I would like to take up this issue next , so if no one else is working on it , kindly assign this to me .

**Comment by sambhavnoobcoder** [comment]
raised a pr #163 that may close this issue , kindly give it a look .

**Comment by Bishoy-at-pieces** [comment]
https://github.com/pieces-app/documentation/blob/main/docs%2Fextensions-plugins%2Fcli%2Fcommands.mdx
@sambhavnoobcoder we need to modify the docs too

**Comment by sambhavnoobcoder** [comment]
okay . on it right way .

**Comment by Bishoy-at-pieces** [comment]
Don't forget to mention that the open command is deprecated

**Comment by sambhavnoobcoder** [comment]
put up a pr at https://github.com/pieces-app/documentation/pull/538 . kindly give it a look and inform me if any changes are required . I'll make those changes asap as well .
