### ISSUE TITLE
Refactoring websockets

### ISSUE THREAD

**Issue by Bishoy-at-pieces** [pieces-app/cli-agent#157]
We will need to refactor all web sockets to inherit from one base 
You can use the base class from the sublime plugin 
https://github.com/pieces-app/plugin_sublime/blob/main/base_websocket.py
This is an amazing implementation and very useful to keep track of the  web sockets 
That will be useful in issue #151

**Comment by sambhavnoobcoder** [comment]
https://github.com/user-attachments/assets/2a31b761-97dd-47cb-9011-f2fa6a7456d2

hey @Bishoy-at-pieces , I went through this issue and I just want to be clear . we basically want to use the websocket form the sublime plugin as a standardised web socket calling throughout this project as well ? in that case I am attaching a video above , for which I have written some dummy test code to see if my changes are working as intended , and if all sits fine , I'll raise the PR for my code as well . we can discuss the rest on code only .

**Comment by Bishoy-at-pieces** [comment]
Yupp the main reason for this is to have control over all websockets 
We have one class and we can know which websocket are connected which are running and so on

**Comment by sambhavnoobcoder** [comment]
okay , I'll raise the PR then asap

**Comment by sambhavnoobcoder** [comment]
raised a PR #166 potentially addressing this issue . kindly give it a look .
