### ISSUE TITLE
Refactor suggestions (for Russian letter)

### ISSUE THREAD

**Issue by lixelv** [pieces-app/cli-agent#158]
For letters, that out of ASCII, suggestions and chat descriptions are formatted wrong. Can be fixed by changing the changing coding to utf-8 (I guess)
![image](https://github.com/user-attachments/assets/014da089-b977-4fb2-9402-69e1e9da228f)

**Comment by Bishoy-at-pieces** [comment]
@lixelv This is the desktop app please report it here: https://github.com/pieces-app/support

this is the Pieces CLI project feel free to check it out

**Comment by lixelv** [comment]
Ok, 👌
