### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sam-at-pieces** [pieces-app/cli-agent#17]
We need to add some unit tests.

**Comment by mark-at-pieces** [comment]
+1 here:
would be solid to have a minimum 1 single test for each of the commands

**Comment by hal-8999-alpha** [comment]
Currently the unit tests are not reading the file directory path correct. 

```
Traceback (most recent call last):
  File "C:\Users\Jayson\cli-agent\tests\app_test.py", line 3, in <module>
    from src.pieces.app import main
ModuleNotFoundError: No module named 'src'
```

**Comment by sam-at-pieces** [comment]
@hal-8999-alpha This is now fixed, you can run the tests from the project root using:
```bash
poetry run pytest
```
