### ISSUE TITLE
Follow Up

### ISSUE THREAD

**Issue by ksubramanyeshwara** [pieces-app/cli-agent#175]
# Follow Up

Can we have a feature where we can ask a follow-up, backspace or esc to exit after executing the first command or first pieces ask with context awareness?

**Comment by Bishoy-at-pieces** [comment]
Yes we already have it
You should be using `pieces run` before the ask command 👍

**Comment by ksubramanyeshwara** [comment]
![Screenshot from 2024-09-01 13-57-13](https://github.com/user-attachments/assets/1dfc02f3-e27a-435b-9c18-d1b3853208ed)

There was no response when I asked questions through `pieces run`. Please take a look.

**Comment by Bishoy-at-pieces** [comment]
Yea noticed that because the CLI is not compatible with the newest Pieces OS Version gonna create a release
