### ISSUE TITLE
Give user options to exit the loop after running the `ask` command

### ISSUE THREAD

**Issue by seantiz** [pieces-app/cli-agent#191]
`pieces ask` works great, but right now I have to interrupt the process with Ctrl + C after getting a query response.

It would be useful if there were options printed on screen to either continue the conversation, close it or exit the CLI app entirely. 

I'd make a PR myself but it wasn't clear where the `ask` command is defined in the `.py` scripts.

**Comment by Bishoy-at-pieces** [comment]
Yeah in the Copilot package, you can work on that issue if you have any question please let me know

**Comment by seantiz** [comment]
> Yeah in the Copilot package, you can work on that issue if you have any question please let me know

Ok i came up with a slightly finicky [solution here](https://github.com/seantiz/pieces-cli-agent/tree/9d6e9db07f3620795591847adf01648308fdb798/exit_all_threads_from_ask)

Let me know what you think. I've held off on creating a PR because:

1. I think the options prompted can be better (instead of choosing Option 1 to submit a new query each time, somehow just keep waiting for new queries unless the user explicitly chooses to exit the app)
2. I could only get all threads to close using an `os._exit(0)` call. `sys.exit(0)` was not closing some top-level loop but I had trouble tracing what thread wasn't closing when using `sys`

**Comment by Bishoy-at-pieces** [comment]
I think this is a great start but if you want to enter a new query in the same conversation you should use the run command instead

**Comment by Bishoy-at-pieces** [comment]
For 2 that is great I will be taking a look into that great work

**Comment by seantiz** [comment]
@Bishoy-at-pieces Thanks!

Ok in the end I've managed to keep the [changes local to app.py](https://github.com/seantiz/pieces-cli-agent/blob/80ee8efbd84b26f053c2013cee9f0d164e9b61c4/exit_all_threads_from_ask/app.py)

The user only needs to type 'exit' to leave the loop, otherwise they're free to continue the conversation with as many queries as wanted.

I haven't figured out a way to close the app on 'exit' without using `os._exit(0)` so that is still in there, but otherwise I can move the changes to `src/pieces/app.py` and create a PR if all looks good.

**Comment by Bishoy-at-pieces** [comment]
@seantiz we already have the run command using pieces run which will do the same thing

**Comment by seantiz** [comment]
> @seantiz we already have the run command using pieces run which will do the same thing

Ok, understood. Sorry I didn't pick that up earlier. So it's just an exit method on the `ask` command that would be useful here?

**Comment by Bishoy-at-pieces** [comment]
If you mean stopping the streaming from the copilot then yes

**Comment by seantiz** [comment]
@Bishoy-at-pieces outside of using `os._exit(0)` i'm not much closer to solving this, but here's some logging on did both before and after the `ask` command runs

```
Current process: psutil.Process(pid=25702, name='Python', status='running', started='15:13:01')
Number of threads: 1
Open files: []
Connections: []
Thread Name: MainThread, ID: 8273228352, Alive: True
```

After (when it is meant to clean up with some code I tried, but still kept running):

```
Current process: psutil.Process(pid=25702, name='Python', status='running', started='15:13:01')
Number of threads: 4
Open files: []
Connections: [pconn(fd=3, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=54013), raddr=addr(ip='127.0.0.1', port=1000), status='ESTABLISHED'), pconn(fd=4, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=54014), raddr=addr(ip='127.0.0.1', port=1000), status='ESTABLISHED')]
**Thread Name: MainThread, ID: 8273228352, Alive: True
Thread Name: Thread-4 (run), ID: 6159314944, Alive: True**
```

I'm not sure where Thread-4 spawns in the app but both that and the main thread are still running when I try some cleaner ways to close them.

**Comment by Bishoy-at-pieces** [comment]
Investing I would check the wrapper code especially the ws of the copilot

**Comment by Bishoy-at-pieces** [comment]
Yeah that would be great
