### ISSUE TITLE
some pieces commands doesn't work when first time installing the extension

### ISSUE THREAD

**Issue by kirollos-at-pieces** [pieces-app/cli-agent#204]
**Issue**:
I downloaded the extension. then entered the command 'pieces version' to see the version downloaded

**Actual Result**: 
The onboarding runs, and the version does not appear

**Expected Result**: 
The version should be displayed in order to verify my installation

_Note: also, several commands don't work when installing the extension for the first time. like 'pieces help'_

**Comment by Bishoy-at-pieces** [comment]
Not a bug but when you first use the plugin the onboarding should start same as the desktop app

**Comment by kirollos-at-pieces** [comment]
> Not a bug but when you first use the plugin the onboarding should start same as the desktop app

What if I want to check the version and do not want to run the onboarding now?
