### ISSUE TITLE
Warnings w/ Pydantic && the SDK when we run a pieces command

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/cli-agent#23]
<img width="725" alt="Screenshot 2024-02-08 at 12 24 50 PM" src="https://github.com/pieces-app/cli-agent/assets/46659689/e082bff5-a525-49da-8f8a-fb5ec4658ff5">

I believe @sam-at-pieces && @Dom-Pieces are on this.

This is a known issue, but want to keep this on here

**Comment by sam-at-pieces** [comment]
@mark-at-pieces @Dom-Pieces @hal-8999-alpha, the latest version of the sdk + cli should solve this. I have built them both on the same verison of pydantic and then added some error handling to cover an edge case where pydantic can't parse the datetime on assets. Would love to see if the update resolves this issue specifically @mark-at-pieces, could you pull and give it a shot when you get the chance

**Comment by hal-8999-alpha** [comment]
This seems solved
