### ISSUE TITLE
Pieces "open" issues after running "pieces list models"

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/cli-agent#26]
Issue:

when I run "pieces open" after a "pieces list models", this will emit "Invalid model index or model index not provided."

when I run "pieces open 1" it will give me a Model ID,

currently the description of this command is 

"  open         - Opens your current or most recent asset
  open x       - Open an asset in a list. The CLI must be running"
  
  which is asset specific, So I would assume this would get my most reset asset
  
  and then pieces open 2 would get the 2nd most reset asset.
  
  
  Let me know if you like some more information.

**Comment by mark-at-pieces** [comment]
<img width="609" alt="Screenshot 2024-02-08 at 12 34 02 PM" src="https://github.com/pieces-app/cli-agent/assets/46659689/22a7603d-e313-439c-b280-bec04135244e">

**Comment by mark-at-pieces** [comment]
What I think that we should do here is just update the copy in the help command to be less about the asset and more about the material. ie if last material list was a model then it will open models, if asset then the open will open asset.

so this is all functioning proper would just update the copy and we will be able to resolve this.

**Comment by hal-8999-alpha** [comment]
Yep, I'll update the copy.
