### ISSUE TITLE
"pieces ask" not returning anything

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/cli-agent#29]
<img width="833" alt="Screenshot 2024-02-08 at 12 53 45 PM" src="https://github.com/pieces-app/cli-agent/assets/46659689/3044f4be-f4fe-4ce6-a349-912b8d692238">

I noticed that you have a 10sec timeout, however this returns nothing is roughly 1 sec

**Comment by shivay-at-pieces** [comment]
It is because the model ID is being sent wrong. 
The correct model id for GPT 3.5 is 6f4c2926-c1b3-462e-91c2-20b076c44b58

current_model = {'6f4c2926-c1b3-462e-91c2-20b076c44b58'} # GPT 3.5

@caleb-at-pieces @mark-at-pieces @jordan-pieces 

We can raise a PR to update the model id

**Comment by hal-8999-alpha** [comment]
Any update on this? Mine is running fine.

**Comment by mark-at-pieces** [comment]
> Any update on this? Mine is running fine.

can use harded coded uuids, because this will be different of every user

**Comment by mark-at-pieces** [comment]
what you will want to do instead is call a /models snapshot, then you will want to iterate of that and get the GPT-3.5 model that has a unique string of 'gpt-3.5'. and then get the uuid of that model and use that, so it is generic for all users.

@hal-8999-alpha

**Comment by shivay-at-pieces** [comment]
Pieces.ModelsApi().modelsSnapshot();
