### ISSUE TITLE
"pieces search GPTInferencePredictionOutput outputForFunctionCalling = await insta --mode ncs"  will fail

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/cli-agent#31]
Couple things here:

This command will fail with this :
<img width="676" alt="Screenshot 2024-02-08 at 1 04 53 PM" src="https://github.com/pieces-app/cli-agent/assets/46659689/000fbfd0-3f1a-490a-aa8a-b653087cb50a">

however this will succeed

<img width="729" alt="Screenshot 2024-02-08 at 1 06 03 PM" src="https://github.com/pieces-app/cli-agent/assets/46659689/5a63a421-e763-4f88-9be9-3d43070b9869">

So:
1. can we update the help command to ensure we have the quotes in the search query
2. I noticed that we are fetching every result that is returned from the searching endpoints. so we should show the list and then just fetch the one that they want to open when/ if they decide to open one of these.
3. also ensure that you have transferables set to false.

**Comment by Bishoy-at-pieces** [comment]
Thanks Mark everything should be working no except we need to add the quotes to the help

**Comment by sambhavnoobcoder** [comment]
@Bishoy-at-pieces I was looking to contribute to this issue , was just wondering if you could clear what all has been addressed here and what needs to be done and where can I find the code that needs to be worked on ?

**Comment by Bishoy-at-pieces** [comment]
Just add to the readme if the query is too big you need to add quotes

**Comment by sambhavnoobcoder** [comment]
pushed a PR  #162  . simple issue , single line added , kindly give it a look .
