### ISSUE TITLE
Add Command For Auto-Generated Commit Messages

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/cli-agent#33]
A nice feature to add would be an auto-generated commit message that runs when a user calls `pieces commit`.

It would just use `git diff` to get the current changes, pass that into the `/qgpt/question` endpoint to get a commit message, and finally run the actual `git commit -m MESSAGE`.

Could also add a flag for pushing as well with `-p` or `--push`.

**Comment by BishoyHanyRaafat** [comment]
I can do it

**Comment by mason-at-pieces** [comment]
Hey @BishoyHanyRaafat! That'd be awesome, let me know if anything comes up that could need some help on our side 👍

**Comment by BishoyHanyRaafat** [comment]
I already finish it but waiting for the sdks to be updated there is an issue in the sdks I created waiting for it to be resolved

**Comment by mason-at-pieces** [comment]
Ah ok, I believe we solved the issue with the python SDK but I will double-check on this.

**Comment by mason-at-pieces** [comment]
We should have a patch for the issues released today or tomorrow. Apologies for the delay but amazing work!

Do you have a link to your repo that I could check out?

**Comment by BishoyHanyRaafat** [comment]
Sure check the forked repo I will push the changes that I made now

**Comment by BishoyHanyRaafat** [comment]
https://github.com/BishoyHanyRaafat/cli-agent

**Comment by mason-at-pieces** [comment]
@BishoyHanyRaafat Could you explain the issue you're having with the SDK?

**Comment by BishoyHanyRaafat** [comment]
Just run it and u will know

**Comment by BishoyHanyRaafat** [comment]
Anyways I ran the old version and call the api using urllib

**Comment by mason-at-pieces** [comment]
Hey @BishoyHanyRaafat, sorry for getting back to you late! So you were able to run it successfully?

Are your changes of using the older SDK version pushed to your forked branch?

**Comment by BishoyHanyRaafat** [comment]
I tried my repo and test it with 1.2.7 version and it was working now no need for the 2.0.0 version for now
