### ISSUE TITLE
Run command to execute a snippet

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/cli-agent#35]
Would be great to add a run command to run bash snippets in the terminal

`pieces run 'Git prune remote branches'`

would run my snippet labeled 'Git prune remote branches'

`git remote prune origin`

**Comment by pridyok** [comment]
I second this. I was really hoping to manage shell snippets with Pieces, but that doesn't really work when there's no way to run the snippets without copy / pasting.

**Comment by sambhavnoobcoder** [comment]
this sounds like an interesting issue . I would like to give it a go , if it is available and not being worked on .

**Comment by sambhavnoobcoder** [comment]
just to be clear , do we want to modify the existing behaviour of the run command to also run the bash snippets , OR do we want to create a new command altogether ?
If it's the former , could you point me to the relevant code?
And if its the latter , is my assumption correct that I would have to create a new file in the commands folder corresponding to this command and then adding the support to call it in the pieces all adequately ?
