### ISSUE TITLE
Search without mode matching everything

### ISSUE THREAD

**Issue by caleb-at-pieces** [pieces-app/cli-agent#42]
when i search 'git' on fts and ncs, i get normal results. when I search without a mode it is matching everything:
<img width="441" alt="image" src="https://github.com/pieces-app/cli-agent/assets/133268200/e17874e9-bf9f-40b1-ac65-970408bcaea1">

**Comment by hal-8999-alpha** [comment]
Searching without a mode defaults to fuzzy search. Is fuzzy search not behaving correctly?

**Comment by caleb-at-pieces** [comment]
> Searching without a mode defaults to fuzzy search. Is fuzzy search not behaving correctly?

Yes, I don't think that using 'git' as a search query should match all my snippets. We might need to adjust something in the fuzzy search package?
