### ISSUE TITLE
Chore: rewrite get_models_ids to use the SDK

### ISSUE THREAD

**Issue by mark-at-pieces** [pieces-app/cli-agent#58]
This is what the function looking like right now in ([file link](https://github.com/pieces-app/cli-agent/blob/b64f73c4add14937a514c7e8ad0d1726cb93273a/src/pieces/api/api_functions.py))

Lets adjust this to use our SDK instead of a custom data structure for the Model.

```python
def get_models_ids() -> Dict[str, Dict[str, Union[str, int]]]:
    # api_instance = pos_client.ModelsApi(api_client)

    # api_response = api_instance.models_snapshot()
    # models = {model.name: {"uuid":model.id,"word_limit":model.max_tokens.input} for model in api_response.iterable if model.cloud or model.downloading} # getting the models that are available in the cloud or is downloaded
    

    
    # call the api until the sdks updated
    response = urllib.request.urlopen('http://localhost:1000/models').read()
    response = json.loads(response)["iterable"]
    models = {model["name"]:{"uuid":model["id"] ,"word_limit" :model["maxTokens"]["input"]} for model in response if model["cloud"] or model["downloading"]}
    return models
```

**Comment by Bishoy-at-pieces** [comment]
These are the foundations that added in 2.0.0 which are not in 1.2.7 
    PHI_1_DOT_5 = 'PHI_1.5'
    PHI_2 = 'PHI_2'
    MIXTRAL_8_X_7_B = 'MIXTRAL_8_x_7B'

**Comment by mason-at-pieces** [comment]
@mark-at-pieces @Bishoy-at-pieces I'm talking with dom on getting our python SDK updated which may solve this. Will send updates as they come.
