### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by hal-8999-alpha** [pieces-app/cli-agent#6]
Enabling searching based on values:

The search endpoint is /search/ncs{query}. 

It focuses on embedded searches on values, not metadata.

**Comment by hal-8999-alpha** [comment]
Search Options:

**/assets/search :** this is considered blended search this will search metadata and will search the snippet content, behind the scenes uses a fuzzy search

**/search/ncs :** this will only search the content and is really solid for snippet comparison as well as searching for semantic meaning with the snippet ie. iterator

**/search/fts:** this is a full text search for the content only

There is also filtering.

**Comment by hal-8999-alpha** [comment]
* Noticed that both search, ncs and fts seem to be case sensitive. For instance, search chatbot and search Chatbot yield different results.

**Comment by mark-at-pieces** [comment]
Do you have some expected inputs / outputs?

Would be awesome for a set of your saved snippets? and the search query
