### ISSUE TITLE
Add a test for the auth commands (login/logout)

### ISSUE THREAD

**Issue by BishoyHanyRaafat** [pieces-app/cli-agent#75]

**Comment by mdex-geek** [comment]
hey i am interested in this problem you tell me about this

**Comment by Bishoy-at-pieces** [comment]
Hey @mdex-geek ,
Let me know how I can help! Checkout the other tests for an idea

**Comment by mdex-geek** [comment]
@Bishoy-at-pieces  i have a question i have to write the code that see that user input user id  and password is correct or not 
?

**Comment by Bishoy-at-pieces** [comment]
No no just check if the command runs properly, check if the website is opened successfully

**Comment by mdex-geek** [comment]
@Bishoy-at-pieces currently cmd is not working properly I check it . 
Bishop I am new in OSS can you help me how can i implement this I clone the project and install the poetry package

**Comment by mdex-geek** [comment]
@mason-at-pieces sorry i disturbing you again and i misunderstand your message. yes the login and logout cmd are working properly

**Comment by mdex-geek** [comment]
@Bishoy-at-pieces Sorry if I'm disturbing you the command login and logout is working properly and I tested it and it work properly .

https://github.com/pieces-app/cli-agent/assets/107706485/dd0c939d-d27d-4773-b9dc-390d3281c74c

**Comment by Bishoy-at-pieces** [comment]
Yes here you should add a test to test this command checkout the /tests directory

**Comment by mdex-geek** [comment]
Where in terminal I add test and you explain me test directory I am  getting little confuse

**Comment by Bishoy-at-pieces** [comment]
https://docs.python.org/3/library/unittest.html

https://github.com/pieces-app/cli-agent/tree/main/tests

**Comment by sambhavnoobcoder** [comment]
@mdex-geek are you looking into this ? if not , then I would like to give this a go .

**Comment by sambhavnoobcoder** [comment]
raised a PR #147 to fix the issue . kindly give it a look .
