### ISSUE TITLE
Copilot - Ask

### ISSUE THREAD

**Issue by hal-8999-alpha** [pieces-app/cli-agent#8]
Use Qgpt API with the Ask command to chat with your current LLM about the context

**Comment by hal-8999-alpha** [comment]
Issue:

Structure
/qgpt/stream
- Requires a QGPTStreamInput
- You can either pass in relevance or question to QGPTStreamInput
- QGPTQuestionInput says it requires a model id and query but when running, 
the error message indicates that you MUST pass in relevant
- I Pass in the query, model and RelevantQGPTSeeds
- RelevantQGPTSeeds has iterable which is a list of RelevantQGPTSeed
- I try creating a blank RelevantQGPTSeed to see what happens and the error changes from saying that relevant is required to:

Error occurred while asking the question: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'x-powered-by': 'Dart with package:shelf', 'access-control-allow-headers': '*', 'date': 'Wed, 03 Jan 2024 00:48:28 GMT', 'x-hacker': "If you're reading this apply at Pieces.app", 'access-control-allow-origin': '*', 'content-length': '15', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'text/plain; charset=utf-8', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff'})

def ask_question(model_id, query="This is a test"):

    ## Try creating a blank seed
    demo_seed = RelevantQGPTSeed()

    ## Add the seed to a list
    iterable = [demo_seed]

    ## Create Instance
    api_instance = openapi_client.QGPTApi(api_client)
    
    ## Create the stream input
    qgpt_stream_input = QGPTStreamInput(
        question=QGPTQuestionInput(
            query=query, model=model_id, relevant=RelevantQGPTSeeds(iterable=iterable)
            ))

    response = api_instance.qgpt_stream(qgpt_stream_input=qgpt_stream_input)
    
    print(response)

**Comment by mark-at-pieces** [comment]
// Sending a message to the WebSocket
  webSocket.add(jsonEncode(
    QGPTStreamInput(
      question: QGPTQuestionInput(
        // query: 'Write a chess game in dart',
        query: 'print hello world in dart',
        relevant: RelevantQGPTSeeds(iterable: []),
        model: _model.id,
      ),
    ),
  ));
  
  
  
  ***Note: the model is not required here

**Comment by mark-at-pieces** [comment]
```dart
final webSocket = await WebSocket.connect('ws://localhost:1000/qgpt/stream');

webSocket.listen((event) {
    QGPTStreamOutput response = QGPTStreamOutput.fromJson(jsonDecode(event)) as QGPTStreamOutput;
    String? text = response.question?.answers.iterable.first.text;
    if (text != null) {
      print(text);
      combined += text;
    }
    if (response.status != null && response.status == QGPTStreamEnum.COMPLETED) {
      print('we are done.');
      conversation = response.conversation;
      if (!processing.isCompleted) {
        processing.complete();
      }
    } else if (response.status != null && response.status == QGPTStreamEnum.STOPPED) {
      print('we we stopped our output.');
      conversation = response.conversation;
      if (!processing.isCompleted) {
        processing.complete();
      }
    } else {
      print(response.status);
      print(response.statusCode);
    }
  });
```

Simple example in dart listening to the websocket.
**NOTE: not production read just for a simple example to test and start to log different outputs
