### ISSUE TITLE
Pieces run command on brew install

### ISSUE THREAD

**Issue by seantiz** [pieces-app/cli-agent#84]
I could not run this command on the current build. When i used `pieces run`  from the terminal, after `brew install` ing `pieces-cli` from the same terminal session, the MacOS kernel comes up with a warning dialog:

_'"pieces: can't be opened because Apple cannot check it for malicious software.

The software needs to be updated. Contact the developer for more information.

Homebrew Cask downloaded this file today at (timestamp)."_

Out of curiosity: it this a Tauri build?

**Comment by Bishoy-at-pieces** [comment]
Don't use Homebrew to download the cli agent just clone the repo and do pip install . Until we ship it I discussed with Mark and it will be shipped soon

**Comment by seantiz** [comment]
ok @Bishoy-at-pieces thanks, I will do!
