### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by joshuadanpeterson** [pieces-app/cli-agent#87]
When I try to run any command or subcommand I get this error

`
Unhandled exception:
Null check operator used on a null value
#0      Application.fromJson (package:runtime_common_library/model/application.dart:111)
#1      Format.fromJson (package:runtime_common_library/model/format.dart:281)
#2      Format.listFromJson (package:runtime_common_library/model/format.dart:304)
#3      AssetFormats.fromJson (package:runtime_common_library/model/asset_formats.dart:83)
#4      Asset.fromJson (package:runtime_common_library/model/asset.dart:305)
#5      Asset.listFromJson (package:runtime_common_library/model/asset.dart:326)
#6      Assets.fromJson (package:runtime_common_library/model/assets.dart:76)
#7      Cacher.cache (package:pieces_cli/src/util/cacher.dart:86)
<asynchronous suspension>
#8      _initChecks (file:///Users/runner/work/pieces-cli/pieces-cli/bin/main.dart:109)
<asynchronous suspension>
#9      main (file:///Users/runner/work/pieces-cli/pieces-cli/bin/main.dart:27)
<asynchronous suspension>
`

Also, typing -h works, but --help doesn't

**Comment by BishoyHanyRaafat** [comment]
How did u install pieces-cli??

**Comment by joshuadanpeterson** [comment]
With Homebrew

**Comment by BishoyHanyRaafat** [comment]
Homebrew is using the old version of the cli agent and it does not work so you can use this github until we ship it

**Comment by joshuadanpeterson** [comment]
Got it. Thanks, that makes sense now.

How do I use the GitHub version? Just clone the repo?

**Comment by BishoyHanyRaafat** [comment]
Do you have python??

**Comment by joshuadanpeterson** [comment]
Yes, of course, isn't that what this cli is?

**Comment by BishoyHanyRaafat** [comment]
Perfect!
1. Clone the repo on your machine 
2. Go to the project cloned directory
3. Do pip install .

You can also check the releases but it is a bit outdated too that is the recommended way for now until we update everything

**Comment by joshuadanpeterson** [comment]
Cloned the repo and ran the install, and now I'm getting this error:

`Traceback (most recent call last):
  File "/Users/joshpeterson/.pyenv/versions/3.11.4/bin/pieces", line 5, in <module>
    from pieces.app import main
  File "/Users/joshpeterson/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pieces/app.py", line 2, in <module>
    from pieces.commands import *
  File "/Users/joshpeterson/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pieces/commands/__init__.py", line 7, in <module>
    from .assets import (update_asset_value,
  File "/Users/joshpeterson/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pieces/commands/assets.py", line 85
    file_path = os.path.join(open_snippet_dir , f"{commands_functions.sanitize_filename(asset["name"])}{commands_functions.get_file_extension(asset["language"])}")
                                                                                               ^^^^
SyntaxError: f-string: unmatched '['`

**Comment by BishoyHanyRaafat** [comment]
Interesting so basically because I use python 3.12 that's why I did not see this error it is a small fix I will create a PR to solve that issue.

**Comment by joshuadanpeterson** [comment]
Cool, thank you

**Comment by BishoyHanyRaafat** [comment]
Yup merged

**Comment by joshuadanpeterson** [comment]
Cool thank you. It works. Now it's just slow to execute lol

**Comment by BishoyHanyRaafat** [comment]
Use pieces run

**Comment by mark-at-pieces** [comment]
> Cool thank you. It works. Now it's just slow to execute lol

how many Pieces do you have saved?

**Comment by mark-at-pieces** [comment]
very well could be some performance issues, that we can take a look into @BishoyHanyRaafat 

lemme know if you want to an eval on performance with myself and @caleb-at-pieces

**Comment by joshuadanpeterson** [comment]
> > Cool thank you. It works. Now it's just slow to execute lol
> 
> how many Pieces do you have saved?

Currently, 201

**Comment by BishoyHanyRaafat** [comment]
> > > Cool thank you. It works. Now it's just slow to execute lol
> > 
> > how many Pieces do you have saved?
> 
> Currently, 201

Currently we are working on make the list command much much fast no worries when the update comes I will mention you

**Comment by joshuadanpeterson** [comment]
@BishoyHanyRaafat Cool, thank you

**Comment by Bishoy-at-pieces** [comment]
@joshuadanpeterson let me know how it is now.
It is a bit slow but it is much much faster 
And I recommend using the run command 
The project is now on pypi `pip install pieces-cli`

**Comment by joshuadanpeterson** [comment]
> @joshuadanpeterson let me know how it is now. It is a bit slow but it is much much faster And I recommend using the run command The project is now on pypi `pip install pieces-cli`

Cool, thank you @Bishoy-at-pieces. It's much much faster

**Comment by Bishoy-at-pieces** [comment]
Next release it will be faster by 2 more sec most probably

**Comment by Bishoy-at-pieces** [comment]
You mind closing that issue?

**Comment by joshuadanpeterson** [comment]
Closing
